# Generated by Django 4.2.1 on 2023-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
