# Generated by Django 4.2.1 on 2023-05-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name_plural": "Comments"},
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment_id",
            field=models.IntegerField(unique=True),
        ),
    ]
