# Generated by Django 4.2.1 on 2023-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0002_alter_comments_options_alter_comments_comment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="id",
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
