# Generated by Django 4.2.1 on 2023-05-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0004_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="author_user_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="p5.users"
            ),
        ),
    ]
