# Generated by Django 4.2.1 on 2023-05-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0005_comments_author_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                (
                    "author_user_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_author_user_id",
                        to="p5.users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projects",
            },
        ),
    ]
