# Generated by Django 4.2.1 on 2023-05-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0006_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                (
                    "project_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors_project_id",
                        to="p5.projects",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="p5.users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contributors",
            },
        ),
    ]
