# Generated by Django 4.2.1 on 2023-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0008_issues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="comment_id",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="created_time",
        ),
        migrations.AddField(
            model_name="comments",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
