# Generated by Django 4.2.1 on 2023-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0009_remove_comments_comment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment_id",
            field=models.IntegerField(null=True),
        ),
    ]
