# Generated by Django 4.2.1 on 2023-05-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0010_comments_comment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
