# Generated by Django 4.2.1 on 2023-05-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("p5", "0013_alter_projects_author_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="author_user_id",
            new_name="author_user",
        ),
    ]
