# Generated by Django 3.2.5 on 2023-05-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0015_auto_20230511_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p5.projects'),
        ),
    ]
