# Generated by Django 3.2.5 on 2023-05-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0017_auto_20230513_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='contributors',
            new_name='contributors_id',
        ),
    ]
