# Generated by Django 3.2.5 on 2023-05-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0018_rename_contributors_projects_contributors_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='contributors_id',
            new_name='contributors',
        ),
    ]
