# Generated by Django 3.2.5 on 2023-05-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0019_rename_contributors_id_projects_contributors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='contributors',
            new_name='contributors_id',
        ),
    ]
