# Generated by Django 3.2.5 on 2023-05-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0022_rename_role_contributors_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='role',
            field=models.CharField(default='.', max_length=255),
            preserve_default=False,
        ),
    ]
