# Generated by Django 3.2.5 on 2023-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0025_alter_contributors_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
