# Generated by Django 3.2.5 on 2023-05-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0029_auto_20230519_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user_id',
            new_name='author',
        ),
    ]
