# Generated by Django 3.2.5 on 2023-05-19 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p5', '0038_alter_projects_author_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='author_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='contributors_id',
            field=models.ManyToManyField(related_name='Project_contributors', through='p5.Contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
