# Generated by Django 3.2.5 on 2023-05-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0040_alter_contributors_project_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together=set(),
        ),
    ]
