# Generated by Django 3.2.5 on 2023-05-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0041_alter_contributors_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project_id',
            new_name='project',
        ),
    ]
