# Generated by Django 3.2.5 on 2023-05-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0042_rename_project_id_issue_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='author_user_id',
            new_name='author',
        ),
    ]
