# Generated by Django 3.2.5 on 2023-05-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0043_rename_author_user_id_projects_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='contributors_id',
            new_name='contributors',
        ),
    ]
