# Generated by Django 3.2.5 on 2023-05-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0045_rename_contributors_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='project_id',
            new_name='project',
        ),
    ]
