# Generated by Django 3.2.5 on 2023-05-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0046_rename_project_id_contributor_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user_id',
            new_name='user',
        ),
    ]
