# Generated by Django 3.2.5 on 2023-05-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0048_rename_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
