# Generated by Django 3.2.5 on 2023-05-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0049_remove_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='project',
        ),
    ]
