# Generated by Django 3.2.5 on 2023-05-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0050_remove_contributor_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
    ]
