# Generated by Django 3.2.5 on 2023-05-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p5', '0053_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contributors_project', to='p5.project'),
            preserve_default=False,
        ),
    ]
