# Generated by Django 3.2.5 on 2023-05-19 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p5', '0054_contributor_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='Project_contributors', through='p5.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
